version: '3.8'

# Упрощенная версия для Portainer
# Убраны все неподдерживаемые опции

services:
  driver-service:
    image: registry.starline.ru/crm-driver-service:latest
    ports:
      - "8001:8001"
    environment:
      - DRIVER_SERVICE_DATABASE_HOST=postgres
      - DRIVER_SERVICE_DATABASE_USER=driver_service
      - DRIVER_SERVICE_DATABASE_PASSWORD=driver_service_password
      - DRIVER_SERVICE_DATABASE_DATABASE=driver_service
      - DRIVER_SERVICE_SERVER_ENVIRONMENT=production
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: driver_service
      POSTGRES_USER: driver_service
      POSTGRES_PASSWORD: driver_service_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
