version: '3.8'

services:
  driver-service:
    image: registry.starline.ru/crm-driver-service:latest
    ports:
      - "8001:8001"
      - "9001:9001"
      - "9002:9002"
    environment:
      - DRIVER_SERVICE_DATABASE_HOST=postgres
      - DRIVER_SERVICE_DATABASE_PORT=5432
      - DRIVER_SERVICE_DATABASE_USER=driver_service
      - DRIVER_SERVICE_DATABASE_PASSWORD=driver_service_password
      - DRIVER_SERVICE_DATABASE_DATABASE=driver_service
      - DRIVER_SERVICE_REDIS_HOST=redis
      - DRIVER_SERVICE_REDIS_PORT=6379
      - DRIVER_SERVICE_NATS_URL=nats://nats:4222
      - DRIVER_SERVICE_SERVER_ENVIRONMENT=production
      - DRIVER_SERVICE_LOGGER_LEVEL=info
      - DRIVER_SERVICE_LOGGER_FORMAT=json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - driver-service-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: driver_service
      POSTGRES_USER: driver_service
      POSTGRES_PASSWORD: driver_service_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U driver_service -d driver_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - driver-service-network

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - driver-service-network

  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    volumes:
      - nats_data:/data
    networks:
      - driver-service-network

volumes:
  postgres_data:
  redis_data:
  nats_data:

networks:
  driver-service-network:
    driver: bridge
