version: '3.8'

# Минимальная production конфигурация без Prometheus/Grafana
# Для случаев, когда внешние файлы недоступны

services:
  driver-service:
    image: registry.starline.ru/crm-driver-service:latest
    ports:
      - "8001:8001"  # HTTP API
      - "9001:9001"  # gRPC API
      - "9002:9002"  # Metrics
    environment:
      - DRIVER_SERVICE_DATABASE_HOST=postgres
      - DRIVER_SERVICE_DATABASE_PORT=5432
      - DRIVER_SERVICE_DATABASE_USER=driver_service
      - DRIVER_SERVICE_DATABASE_PASSWORD=driver_service_password
      - DRIVER_SERVICE_DATABASE_DATABASE=driver_service
      - DRIVER_SERVICE_REDIS_HOST=redis
      - DRIVER_SERVICE_REDIS_PORT=6379
      - DRIVER_SERVICE_NATS_URL=nats://nats:4222
      - DRIVER_SERVICE_SERVER_ENVIRONMENT=production
      - DRIVER_SERVICE_LOGGER_LEVEL=warn
      - DRIVER_SERVICE_LOGGER_FORMAT=json
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: rollback
        order: start-first
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    networks:
      - driver-service-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: driver_service
      POSTGRES_USER: driver_service
      POSTGRES_PASSWORD: driver_service_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U driver_service -d driver_service"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - driver-service-network

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - driver-service-network

  nats:
    image: nats:2.10-alpine
    ports:
      - "14222:4222"  # Client connections
      - "18222:8222"  # HTTP management
    command: ["-js", "-m", "8222"]
    volumes:
      - nats_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/varz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - driver-service-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  nats_data:
    driver: local

networks:
  driver-service-network:
    driver: overlay
    attachable: true
