version: '3.8'

services:
  test-postgres:
    image: postgres:15-alpine
    container_name: driver-service-test-postgres
    environment:
      POSTGRES_DB: driver_service_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"  # Другой порт для тестов
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d driver_service_test"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - test-network

  test-redis:
    image: redis:7-alpine
    container_name: driver-service-test-redis
    ports:
      - "6380:6379"  # Другой порт для тестов
    volumes:
      - test_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - test-network

volumes:
  test_postgres_data:
  test_redis_data:

networks:
  test-network:
    driver: bridge
